Repository cBioPortal/clinical-data-dictionary, pull requests merged in 2018-03, with the labels that each got.

#3 Fix so that war file works
  src/main/java/org/cbioportal/cam/ClinicalAttributeMetadataApplication.java
Labels: bug

#10 exclude clashing guava dependency
  pom.xml
Labels: bug, repository

#14 Add example logback.xml and filter example files from war
  pom.xml
  src/main/resources/logback.xml.EXAMPLE
Labels: docs

#15 Endpoint to force a refresh of the cache
  src/main/java/org/cbioportal/cdd/service/ClinicalDataDictionaryService.java
  src/main/java/org/cbioportal/cdd/service/internal/ClinicalAttributeMetadataCache.java
  src/main/java/org/cbioportal/cdd/service/internal/ClinicalDataDictionaryServiceImpl.java
  src/main/java/org/cbioportal/cdd/web/ClinicalDataDictionaryController.java
  src/test/java/org/cbioportal/cdd/ClinicalDataDictionaryTest.java
  src/test/java/org/cbioportal/cdd/ClinicalDataDictionaryTestConfig.java
Labels: controller, enhancement
